name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    uses: ./.github/workflows/setup-node.yml
    with:
      script: npm run lint

  typecheck:
    uses: ./.github/workflows/setup-node.yml
    with:
      script: npm run typecheck

  build:
    needs: [lint, typecheck]
    uses: ./.github/workflows/setup-node.yml
    with:
      script: npm run build

  test:
    needs: [lint, typecheck]
    uses: ./.github/workflows/setup-node.yml
    with:
      script: npm run test

  docker-build:
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
      - uses: actions/checkout@v3
      - run: docker build -t my-app:latest .
