name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  setup:
    uses: ./.github/workflows/setup-node.yml

  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Run ESLint
        run: npm run lint

  typecheck:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Run TypeScript check
        run: npm run typecheck

  build:
    needs: [lint, typecheck]
    runs-on: ubuntu-latest
    steps:
      - name: Build project
        run: npm run build

  test:
    needs: [lint, typecheck]
    runs-on: ubuntu-latest
    steps:
      - name: Run unit tests
        run: npm run test
